runtime: nodejs16

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  JWT_EXPIRES_IN: "7d" 

includes:
  - env_variables.yaml
  # Do NOT include sensitive environment variables here
  # We'll set them through the Cloud Console

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  max_instances: 2
  min_pending_latency: automatic
  max_pending_latency: automatic
  target_cpu_utilization: 0.65