steps:
  # Install dependencies
  - name: 'node:16'
    entrypoint: npm
    args: ['install']
    
  # Create env_variables.yaml with secrets from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "env_variables:" > env_variables.yaml
        echo "  MONGODB_URI: \"$$MONGODB_URI\"" >> env_variables.yaml
        echo "  JWT_SECRET: \"$$JWT_SECRET\"" >> env_variables.yaml
        echo "  JWT_EXPIRES_IN: \"7d\"" >> env_variables.yaml
        echo "  ADMIN_TOKEN: \"$$ADMIN_TOKEN\"" >> env_variables.yaml
    secretEnv: ['MONGODB_URI', 'JWT_SECRET', 'ADMIN_TOKEN']
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=${_VERSION}']
    
substitutions:
  _VERSION: v1-${SHORT_SHA}
  
# This fixes the error by specifying how to handle logs
options:
  logging: CLOUD_LOGGING_ONLY
  
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/MONGODB_URI/versions/latest
      env: 'MONGODB_URI'
    - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET/versions/latest
      env: 'JWT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/ADMIN_TOKEN/versions/latest
      env: 'ADMIN_TOKEN'